version: '3.6'
services:
    # web is bundling php-fpm & nginx
    web:
        build:
            context: ./.provision
        depends_on:
            - db
            - redis
        environment:
            DATABASE_URL: postgres://postgres:supersecret@db:5432/default
            PHP_IDE_CONFIG: "serverName=php.local"
        extra_hosts:
            - "host.docker.internal:${XDEBUG_REMOTE_HOST}"
        image: php-fpm-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
    db:
        image: postgres:alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER:     postgres
            POSTGRES_PASSWORD: supersecret
            POSTGRES_DB:       default
        volumes:
            - pgdata:/var/lib/postgresql/data
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
    adminer:
        image: adminer
        ports:
            - 8081:8080
volumes:
    pgdata: {}
